version: '3'

services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  redis-commander:
    depends_on:
      - redis
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  github-api:
    depends_on:
      - redis
    build: .
    restart: always
    environment:
      - REST_API_ENDPOINT=https://api.github.com/
      - REST_TIMEOUT=4000
      - REDIS_CACHE_IS_ENABLED=true
      - REDIS_CACHE_HOST=redis
      - REDIS_CACHE_PORT=6379
      - REDIS_CACHE_TTL_MS=86400000
      - SERVING_PORT=3001
    ports:
      - "3001:3001"
